health-check: ensure LC_ALL for logstash curator
On rhel system, curator fails with:

RuntimeError: Click will abort further execution because Python 3 was configured
to use ASCII as encoding for the environment.

This change ensure LC_ALL is set to en_US.UTF8

Change-Id: Iecd69a518de160ad0579616f96bf27c9d0e65fc9