Fix queue name usage and missing pwt
Latest zuul version raise this issue:
  extra keys not allowed @ data['gate']['queue']

This change tries to fix the following issue happening on the managesf gate:
  Unable to freeze job graph: Job sf-rpm-publish depends on wait-for-changes-ahead which was not run.

The two jobs should exist since managesf use both template.

This change also fix the following test failure:
  ModuleNotFoundError: No module named 'jwt'

And this linter failure:
  tests/functional/test_log_indexed.py:174:24: E741 ambiguous variable name 'l'

Change-Id: I580ab8399841f0c084cd5019577f7c0d120cf325